language: csharp
solution: PolySerializer.sln
mono: none
dotnet: 3.1.401

install:
- nuget restore PolySerializer.sln
- nuget install NUnit -Version 3.12.0 -OutputDirectory packages
- nuget install NUnit.ConsoleRunner -Version 3.11.1 -OutputDirectory packages
#- nuget install DeepEqual -Version 2.0.0 -OutputDirectory packages

script:
- dotnet restore
#- cat ./PolySerializer/obj/project.assets.json
- msbuild /p:Configuration=Travis PolySerializer.sln
#- cp ./packages/NUnit.3.8.1/lib/net45/nunit.framework.dll ./PolySerializer/bin/x64/Travis/
#- cp ./packages/DeepEqual.1.6.0.0/lib/net40/DeepEqual.dll ./PolySerializer/bin/x64/Travis/
#- dotnet publish Test-PolySerializer -c Travis /p:Platform=x64 -o ./Test-PolySerializer/publish/x64/Travis
#- ls ./packages
#- ls ./Test-PolySerializer/bin/x64/Travis/netstandard2.0
#- cp ./packages/DeepEqual.2.0.0/lib/netstandard2.0/DeepEqual.dll ./Test-PolySerializer/bin/x64/Travis/netstandard2.0
#- mono ./packages/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe --trace=Debug --labels=Before ./Test-PolySerializer/bin/x64/Travis/netstandard2.0/Test-PolySerializer.dll
- dotnet test ./Test-PolySerializer/Test-PolySerializer.csproj

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./PolySerializer/bin/x64/Travis
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master
